feat(home-manager): add support for dunst
catppuccin/nix pull request #104
Opened 2024-04-09 20:30 UTC by henrisota

Adds support for dunst. Resolves #99

2024-04-10 05:38 UTC, getchoo requested changes

2024-04-10 05:38 UTC, getchoo commented on modules/home-manager/dunst.nix
> +      (lib.ctp.fromINI (sources.dunst + /themes/${cfg.flavour}.conf));
```suggestion
  config.services.dunst = lib.mkIf enable {
    settings = lib.ctp.fromINI (sources.dunst + /themes/${cfg.flavour}.conf);
  };
```

2024-04-10 07:03 UTC, henrisota commented on modules/home-manager/dunst.nix
> +      (lib.ctp.fromINI (sources.dunst + /themes/${cfg.flavour}.conf));
Commited with the change.

2024-04-11 04:40 UTC, getchoo approved these changes
thanks :)

2024-04-11 04:40 UTC, merged