feat(nixos): add support for gitea/forgejo
catppuccin/nix pull request #179
Opened 2024-05-20 11:11 UTC by Lichthagel

Requires fetching release artifacts or building the theme from source (similar to #149)

2024-12-30 10:00 UTC, isabelroses commented
This should now be possible!

2025-02-02 22:17 UTC, getchoo commented on modules/nixos/gitea.nix
> +  generateConfig =
Nit, but I'd prefer this to be inlined below rather than it's own lambda

2025-02-02 22:17 UTC, getchoo commented on modules/nixos/gitea.nix
> +        '';
Why not uses systemd-tmpfiles?

2025-02-02 22:17 UTC, getchoo commented on modules/nixos/gitea.nix
> +          builtinThemes.${forge}
Do we really have to enumerate these? It doesn't seem like the port's example `app.ini` specifies them

2025-02-02 22:17 UTC, getchoo commented on pkgs/gitea/package.nix
> +    sha256 = "sha256-14XqO1ZhhPS7VDBSzqW55kh6n5cFZGZmvRCtMEh8JPI=";
```suggestion
    hash = "sha256-14XqO1ZhhPS7VDBSzqW55kh6n5cFZGZmvRCtMEh8JPI=";
```

2025-02-02 22:17 UTC, getchoo commented on pkgs/gitea/package.nix
Pretty sure this file could just be a `fetchzip` call, unless we really want that `meta` attribute from `buildCatppuccinPort`. Up to you

2025-02-02 22:17 UTC, getchoo commented on pkgs/gitea/package.nix
> +    mv * $out
```suggestion
    ln -s $src $out
```
Pretty sure this would work. It's a bit neater too

2025-02-02 22:17 UTC, getchoo commented on modules/lib/default.nix
Can't say I'm a fan of introducing a general `consts` just for this

Maybe access them through `types.flavors.functor.payload.values` instead?
Now that I type it out it does sound a bit silly, though...

2025-02-03 09:46 UTC, isabelroses commented on modules/nixos/gitea.nix
> +          builtinThemes.${forge}
Catppuccin doesn't list them but I know from my own instance that if we don't the user does not get the builtin themes available.

2025-02-03 09:47 UTC, isabelroses commented on modules/lib/default.nix
I wasn't a fan either hence I wanted to prompt you for a review. Strictly speaking we could drop it again and use IFD. But I'd rather avoid introducing more IFD.

2025-02-11 06:38 UTC, getchoo commented on modules/nixos/gitea.nix
> +          builtinThemes.${forge}
Ah that sucks :(

2025-02-11 06:39 UTC, getchoo commented on modules/lib/default.nix
I think `types.flavors.functor.payload.values` would be fine for now then, even though it's *super* ugly

If more ports end up using it later, I'd be fine with a `consts`

2025-02-11 06:39 UTC, getchoo commented
Sorry for the wait again, I've been setting up my own Forgejo instance for a little bit and figured it would be the perfect place to test this out. I'll hopefully get to it soon :p

2025-02-17 20:06 UTC, getchoo commented on modules/nixos/gitea.nix
> +            })
```suggestion
            ++ (lib.mapCartesianProduct ({ flavor, accent }: "catppuccin-${flavor}-${accent}") (
              lib.mapAttrs (lib.const valuesFromEnum) {
                inherit (catppuccinLib.types) accent flavor;
              }
            ))
```

2025-02-17 20:06 UTC, getchoo commented on modules/nixos/gitea.nix
> +  inherit (config.catppuccin) sources;
This goes unused...

2025-02-17 20:06 UTC, getchoo commented on modules/nixos/gitea.nix
> +        };
I'm *pretty sure* this is just making this directory a symlink to itself?

2025-02-17 20:13 UTC, isabelroses commented on modules/nixos/gitea.nix
> +        };
yeah i just noticed this should be `sources.gitea`

2025-02-17 21:08 UTC, isabelroses commented
> Sorry for the wait again, I've been setting up my own Forgejo instance for a little bit and figured it would be the perfect place to test this out. I'll hopefully get to it soon :p

On this note. Just deployed my git instance with the theme and it works perfectly.

2025-02-19 03:02 UTC, getchoo requested changes
With the following applied it works on my Forgejo instance as well :)

2025-02-19 03:11 UTC, getchoo approved these changes
Thanks for your work @Lichthagel and @isabelroses. Sorry for the long wait, too

2025-02-19 03:12 UTC, merged