feat(home-manager): add support for spotify-player
catppuccin/nix pull request #296
Opened 2024-07-28 17:12 UTC by w-lfchen

I have an issue with the theme:
The `playback_metadata` component has the same color as the background and is therefore not legible.
But this should be fixed in the [catppuccin repo](https://github.com/catppuccin/spotify-player), right?

2024-08-07 01:05 UTC, getchoo requested changes
This should also add a new entry to `tests/home.nix` enabling the module

> But this should be fixed in the [catppuccin repo](https://github.com/catppuccin/spotify-player), right?

And yep!

2024-08-07 01:05 UTC, getchoo commented on modules/home-manager/spotify-player.nix
> +      themes = (lib.importTOML "${sources.spotify-player}/theme.toml").themes;
```suggestion
      inherit (lib.importTOML "${sources.spotify-player}/theme.toml") themes;
```

2024-08-15 04:56 UTC, w-lfchen commented
didn't mean to make the ci status disappear by updating the branch ^^'
here are the results of the run:
https://github.com/catppuccin/nix/actions/runs/10280254042

2024-08-19 06:25 UTC, getchoo approved these changes
Thanks!

2024-08-19 06:26 UTC, merged