fix: k9s on darwin with xdg disabled
catppuccin/nix pull request #311
Opened 2024-08-13 00:54 UTC by alejandro-angulo

k9s expects configuration files on OS X to live in `~/Library/Application Support/k9s` instead of `~/.config.k9s`. This commit handles the case where the module is built for a darwin system with xdg disabled.

See: https://github.com/catppuccin/nix/issues/310

2024-08-13 17:19 UTC, alejandro-angulo commented
I ran into a similar issue with lazygit (see #312 ). Would it be easier to maintain this flake if there were an assertion ensuring XDG is enabled rather than sprinkling in darwin checks?

2024-08-13 18:34 UTC, m-wynn commented
This worked for me as expected on Darwin both with and without xdg.

2024-08-19 01:25 UTC, getchoo requested changes
It would probably be better to follow the [upstream module](https://github.com/nix-community/home-manager/blob/2598861031b78aadb4da7269df7ca9ddfc3e1671/modules/programs/k9s.nix#L180)'s example here

This should also be formatted with `nixfmt-rfc-style`

2024-08-19 01:25 UTC, getchoo commented on modules/home-manager/k9s.nix
> +  inherit (pkgs.stdenv.hostPlatform) isDarwin;
```suggestion
```

2024-08-19 01:25 UTC, getchoo commented on modules/home-manager/k9s.nix
>    enable = cfg.enable && config.programs.k9s.enable;
```suggestion
  enable = cfg.enable && config.programs.k9s.enable;
  
  # NOTE: On MacOS specifically, k9s expects it's configuration to be in
  # `~/Library/Application Support` when not using XDG
  enableXdgConfig = !pkgs.stdenv.hostPlatform.isDarwin || config.xdg.enable;
```

2024-08-19 01:25 UTC, getchoo commented on modules/home-manager/k9s.nix
> +  themePath = "${configDirectory}/skins/${themeFile}";
```suggestion
  themePath = "k9s/skins/${themeFile}";
```

2024-08-19 01:25 UTC, getchoo commented on modules/home-manager/k9s.nix
>    };
```nix
  config = lib.mkIf enable (
    lib.mkMerge [
      (lib.mkIf (!enableXdgConfig) {
        home.file."Library/Application Support/${themePath}".source = theme;
      })
      (lib.mkIf enableXdgConfig { xdg.configFile.${themePath}.source = theme; })

      { programs.k9s.settings.k9s.ui.skin = themeName; }
    ]
  );
```

2024-08-20 05:31 UTC, getchoo requested changes

2024-08-20 05:31 UTC, getchoo commented on modules/home-manager/k9s.nix
> +  config = lib.mkIf enable lib.mkMerge [
```suggestion
  config = lib.mkIf enable (lib.mkMerge [
```

2024-08-20 05:31 UTC, getchoo commented on modules/home-manager/k9s.nix
> +  ];
```suggestion
  ]);
```

2024-08-23 10:52 UTC, getchoo approved these changes
Thanks!

2024-08-23 10:53 UTC, merged