feat(home-manager): add support for freetube
catppuccin/nix pull request #327
Opened 2024-08-31 21:23 UTC by Anomalocaridid

Adds support for theming FreeTube. The colors are built-in, so no new sources have been added.

Also, FreeTube supports two different accent colors, so I added a `secondaryAccent` option. I made it default to FreeTube's `accent` rather than the global `accent` setting because it seemed like it would be intuitive behavior to have them match if, say, only `accent` is overridden.

2024-09-05 04:22 UTC, getchoo requested changes

2024-09-05 04:22 UTC, getchoo commented on modules/home-manager/freetube.nix
> +  inherit (lib.ctp) mkAccentOpt mkUpper;
```suggestion
  inherit (config.programs.freetube.settings) baseTheme;
  inherit (lib.ctp) mkAccentOpt mkUpper;
```

2024-09-05 04:22 UTC, getchoo commented on modules/home-manager/freetube.nix
> +  config.programs.freetube.settings = lib.mkIf enable rec {
```suggestion
  config.programs.freetube.settings = lib.mkIf enable {
```

2024-09-21 20:29 UTC, getchoo approved these changes
LGTM. Sorry for the long wait and thanks!

2024-09-21 20:29 UTC, merged

2024-09-21 21:12 UTC, Anomalocaridid commented
No worries! Thank you too!