feat(home-manager): init wlogout module
catppuccin/nix pull request #398
Opened 2024-12-09 01:39 UTC by Anomalocaridid

Adds support for wlogout.

Extra options I added:
- `iconStyle`, which lets the user specify whether to use the wlogout or wleave-style icons that come with the theme.
- `extraStyle`, which lets the user add extra CSS to ~/.config/wlogout.css

In order for the svg icons to display properly, [`pkgs.librsvg`](https://search.nixos.org/packages?channel=unstable&show=librsvg&from=0&size=50&sort=relevance&type=packages&query=librsvg) needs to be in [`programs.gdk-pixbuf.modulePackages`](https://search.nixos.org/options?channel=unstable&show=programs.gdk-pixbuf.modulePackages&from=0&size=50&sort=relevance&type=packages&query=gdk-pixbuf), but I am not sure if I should add an assertion or warning or something or just go without.

2024-12-09 10:07 UTC, isabelroses reviewed
If it needs additional packages it maybe worth waiting for https://github.com/catppuccin/nix/pull/384.

I would also prefer not to merge any PRs adding new modules until https://github.com/catppuccin/nix/pull/371 is merged too.

2024-12-10 00:02 UTC, Anomalocaridid commented
@isabelroses Makes sense. In that case, I will mark this as a draft for now.

2024-12-27 21:50 UTC, Anomalocaridid commented
I have updated this PR to reflect the recent treewide changes.

2024-12-30 09:59 UTC, isabelroses requested changes

2024-12-30 09:59 UTC, isabelroses commented on modules/home-manager/wlogout.nix
> +  enable = cfg.enable && config.programs.wlogout.enable;
We have started to remove this from modules that use `.enable` like so 
https://github.com/nix-community/home-manager/blob/10e99c43cdf4a0713b4e81d90691d22c6a58bdf2/modules/programs/wlogout.nix#L73
```suggestion
```

2024-12-30 09:59 UTC, isabelroses commented on modules/home-manager/wlogout.nix
> +  config = lib.mkIf enable {
```suggestion
  config = lib.mkIf cfg.enable {
```

2024-12-31 08:21 UTC, isabelroses approved these changes

2024-12-31 08:34 UTC, merged