docs(FAQ): move to catppuccin namespace
catppuccin/nix pull request #423
Opened 2024-12-26 02:46 UTC by 42willow

* https://github.com/catppuccin/nix/pull/371

2024-12-26 09:01 UTC, isabelroses requested changes
I think we should use full links rather then relative links, such that people using github to view the files, or people who have the repo cloned know where to find things.

2024-12-26 09:01 UTC, isabelroses commented on docs/src/faq.md
> +  A: You can find programs supported through home-manager [here](search/rolling/?scope=home-manager+modules),
```suggestion
  A: You can find programs supported through home-manager [here](https://nix.catppuccin.com/search/rolling/?scope=home-manager+modules),
```

2024-12-26 09:01 UTC, isabelroses commented on docs/src/faq.md
> +  and NixOS modules [here](search/rolling/?scope=NixOS+modules)
```suggestion
  and NixOS modules [here](https://nix.catppuccin.com/search/rolling/?scope=NixOS+modules)
```

2024-12-26 09:01 UTC, isabelroses commented on docs/src/faq.md
> +  A: You can set `catppuccin.enable` [globally](search/rolling/?option_scope=0&option=catppuccin.enable)
```suggestion
  A: You can set `catppuccin.enable` [globally](https://nix.catppuccin.com/search/rolling/?option_scope=0&option=catppuccin.enable)
```

2024-12-27 01:44 UTC, getchoo approved these changes
Thanks!

2024-12-27 01:45 UTC, merged