fix(home-manager/hyprland): source theme colors
catppuccin/nix pull request #80
Opened 2024-02-08 23:42 UTC by Liassica

Since Home Manager commit defbb9c, Hyprland on Home Manager sources external files before most other configuration by default, meaning ctp-nix can now source a theme colors file instead of inserting them into the main configuration.

2024-02-09 03:14 UTC, Anomalocaridid commented
If files are sourced first, would it be possible to implement an accent option that sets Hyprland variables named something like `$accent` and `$accentAlpha` to the corresponding variables for your accent color?

For example, if your accent is red, would the below lines work if the module added them to your Hyprland config?
```hypr
$accent=$red
$accentAlpha=$redAlpha
```

2024-02-10 19:06 UTC, Liassica commented
Added that. Currently it's implemented as a second sourced file, as variables are one of the only configuration that gets placed before `source` entries, so they can't just be added with `hyprland.settings`.

2024-03-13 22:50 UTC, getchoo requested changes

2024-03-13 22:50 UTC, getchoo commented on modules/home-manager/hyprland.nix
> +  ];
```suggestion
  config.wayland.windowManager.hyprland.settings = lib.mkIf enable {
    source = [
      "${sources.hyprland}/themes/${cfg.flavour}.conf"
      (builtins.toFile "hyprland-${cfg.accent}-accent.conf" ''
        $accent=''$${cfg.accent}
        $accentAlpha=''$${cfg.accent}Alpha
      '')
    ];
  };
```

2024-04-10 05:49 UTC, getchoo commented
sorry for the wait! it seems this branch has fallen a bit behind and is still stuck with a bug that's been fixed; could this be rebased?

2024-04-10 22:29 UTC, Liassica commented
Done! I also updated the commit description a bit since this is an official Catppuccin repository now.

2024-05-08 00:35 UTC, getchoo approved these changes
so sorry for the long wait. thanks so much!

2024-05-08 00:36 UTC, merged